import 'dotenv/config.js'
import '../../config/database.js'
import Itinerary from '../Itinerary.js'

const itineraries = [
    {
        _id: '5ca1b6a90193271048449001',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449002',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449003',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449004',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449005',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449006',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449007',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449008',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449009',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449010',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449011',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449012',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449013',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449014',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449015',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449016',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449017',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449018',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449019',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449020',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449021',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449022',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449023',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449024',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449025',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449026',
        name_itinerary: 'City Tour',
        name_user: 'Carlos Mendoza',
        photo: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/OQBPUDYBHNECVAHSYGAUPSORTM.jpg',
        price: '$ 50',
        duration: '2:00 hours',
        likes: 5,
        hashtags: '#city #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449027',
        name_itinerary: 'Tour of a small town in Paisa',
        name_user: 'Camila Restrepo',
        photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
        img_itinerary:
            'https://lulocolombia.travel/wp-content/uploads/2020/05/Square-of-Pueblito-Paisa-Landscape-Medellin-Lulo-Colombia-Travel.jpg',
        price: '$ 80',
        duration: '1:00 hours',
        likes: 8,
        hashtags: '#smallTown #route #visit',
    },
    {
        _id: '5ca1b6a90193271048449028',
        name_itinerary: 'Temple And Shrine',
        name_user: 'Natsuki Suzuki',
        photo: 'https://i.pinimg.com/736x/d9/8f/80/d98f80c4b917e6ef6839845f11bd27d7.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-XsmxwQS/0/6de89f12/L/i-XsmxwQS-L.jpg',
        price: '$ 60',
        duration: '3: 00 hours',
        likes: 80,
        hashtags: '#templeshrine #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449029',
        name_itinerary: 'Climbing Or Visiting Mount Fuji',
        name_user: 'Manabu Yoshida',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/el-japones-mas-guapo-del-mundo-768x681.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-3v8JPVL/0/9f32b8d9/L/i-3v8JPVL-L.jpg',
        price: '$ 65',
        duration: '3: 20 hours',
        likes: 50,
        hashtags: '#mountfuji #japan #tour'
    },
    {
        _id: '5ca1b6a90193271048449030',
        name_itinerary: 'Tokyo Shopping',
        name_user: 'Osamu Yamagawa',
        photo: 'https://www.japonalternativo.com/wp-content/uploads/2022/05/cantantes-japoneses-bellos-bonitos.jpg',
        img_itinerary: 'https://photos.smugmug.com/photos/i-DFsPxSD/0/f534c30a/L/i-DFsPxSD-L.jpg',
        price: '$ 69',
        duration: '3: 30 hours',
        likes: 66,
        hashtags: '#shopping #japan #tour'
    }
]

Itinerary.insertMany(itineraries)
